### PR TITLE
Add variation text when `include_text` is enabled

### PR DESCRIPTION
**Pull request by montlebalm**
Add variation text (e.g., `:skin-tone-2:`) alongside emoji text when `include_text` is enabled. This allows the full colon name to be selected when copying HTML that includes an emoji span.

Other changes:
- Moving `emoji_span` helper function into the test preamble and removing it from individual spec files.

Happy to make any changes to accommodate style or process preferences.

### CODE REVIEW

**Comment by iamcal** [comment]
can you remove the change to the emoji-data sha? i'd like to keep the data version stable here.

if you think this warrants a minor version bump, please roll up the notes from 3.0.3 into 3.1.0 insce i never cut that release

**Comment by montlebalm** [comment]
I could go either way on the version. It does change existing behavior someone might rely on, but it's admittedly minor and could be considered a bug fix.

**Comment by montlebalm** [comment]
@iamcal I reverted the change to emoji-data and rolled up the notes from 3.0.3 into 3.1.0.

**Comment by iamcal** [comment]
merged, thanks!

**Pull request merged**
