### PR TITLE
Add colon_aliases setting

### PR DESCRIPTION
**Pull request by jwheare**
Usage:

emoji.colon_aliases = {
    '1f415': 'doge',
    '1f346': 'aubergine',
    '1f389': 'party_popper'
}

### CODE REVIEW

**Comment by iamcal** [comment]
i like the idea, but will probably do some renaming. we already internally (at slack) have a way to add custom emoji to the list (colon->image mapping) and i want to try and name stuff sanely.

**Comment by jwheare** [comment]
I'm getting round to updating our fork, any updates on your alternative solution or shall I just keep maintaining this patch internally?

**Comment by iamcal** [comment]
PR #56 just merged to master with an api for aliases - does that work for you?

**Comment by jwheare** [comment]
Yup looks good, thanks!

**Pull request closed without merging**
