### PR TITLE
Add support for react-native

### PR DESCRIPTION
**Pull request by xanderberkein**
This library threw a fatal error in `emoji.prototype.init_env`, because navigator.userAgent is undefined in a react-native project.

```js
var ua = navigator.userAgent;
if (ua.match(/(iPhone|iPod|iPad|iPhone\s+Simulator)/i)){
```

This merge requests adds a check for react-native projects and initializes accordingly.

### CODE REVIEW

**Comment by jasondibenedetto** [comment]
Any update on getting this on master?

**Comment by jasondibenedetto** [comment]
@xanderberkein Are you able to rebase and fix the indentation on this PR.

**Comment by xanderberkein** [comment]
@jasondibenedetto I'm a bit busy at the moment, but go ahead and do a new PR if you wish!

**Comment by devpascoe** [comment]
may we have React Native support merged please, thanks

**Comment by karltaylor** [comment]
Would be great to get this merged! 👍

**Comment by abrantes01** [comment]
Any news about this PR ? Would be great for RN support :)

**Comment by iamcal** [comment]
merged in #122

**Pull request closed without merging**
